name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
